table 'gold dim_entity'
	lineageTag: 5b775524-802a-4ee2-9a62-407518d3eb35

	column entity_id
		dataType: string
		lineageTag: 1a032f52-da26-41ab-ad2e-3409cff06aa5
		summarizeBy: none
		sourceColumn: entity_id

		annotation SummarizationSetBy = Automatic

	column entity_code
		dataType: string
		lineageTag: fec76f88-deb1-4a99-b114-d211a2d2d3b5
		summarizeBy: none
		sourceColumn: entity_code

		annotation SummarizationSetBy = Automatic

	column entity_description
		dataType: string
		lineageTag: ebc5babe-731e-4b29-9de7-5ec71883e4c0
		summarizeBy: none
		sourceColumn: entity_description

		annotation SummarizationSetBy = Automatic

	column created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 91e0a229-27bc-42ef-bf06-38d92679dec3
		summarizeBy: none
		sourceColumn: created_on

		variation Variation
			isDefault
			relationship: 4e589d4e-c0ec-438e-bc08-f54d6e34e5ac
			defaultHierarchy: LocalDateTable_c076b519-ec05-4f79-8a14-453740563d53.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column last_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c425766-1fc9-474c-ac4a-bd0f26c591af
		summarizeBy: none
		sourceColumn: last_updated_on

		variation Variation
			isDefault
			relationship: 00839173-2ea4-4896-bc66-5e1172f3f588
			defaultHierarchy: LocalDateTable_2a0e3b6d-a975-420a-a826-b0891ff30274.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column entity_title
		dataType: string
		lineageTag: 7446373c-5545-403b-b093-c32870465273
		summarizeBy: none
		sourceColumn: entity_title

		annotation SummarizationSetBy = Automatic

	partition 'gold dim_entity' = m
		mode: import
		source =
				let
				    Source = Sql.Database(p_SQL_Server, "Relm_Gold_Warehouse"),
				    gold_coverage_view = Source{[Schema="gold",Item="dim_relm_entity"]}[Data],
				    #"Added Custom" = Table.AddColumn(gold_coverage_view, "entity_title", each if [entity_code] = "Relm Ins UK Ltd" then "Relm U.K." else if [entity_code] = "Relm Insurance Ltd." then "Relm Bermuda" else if [entity_code] = "Relm Insurance MENA Ltd." then "Relm MENA" else if [entity_code] = "Relm US Insurance Solutions Inc." then "Relm U.S." else if [entity_code] = "Relm Insurance Agency Inc." then "Relm U.S." else if [entity_code] = "Relm US Insurance Agency" then "Relm U.S." else "Others")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

