table 'gold dim_line_of_business'
	lineageTag: fe53dd89-3b1c-412e-97e4-8abac6c26e95

	column LoB
		dataType: string
		lineageTag: cfb736be-3ab6-4485-97e3-4dc929b5a2b7
		summarizeBy: none
		sourceColumn: LoB
		sortByColumn: LoB_id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column LoB_id
		dataType: int64
		formatString: 0
		lineageTag: 5a80df0a-d723-48c3-8604-bf08db97c47b
		summarizeBy: sum
		sourceColumn: LoB_id

		annotation SummarizationSetBy = Automatic

	partition 'gold dim_line_of_business' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wck4sLk3MKalU0lEyVIrVAQoUZeamAnlGEF5lUmoRkGcM5rll5iXmJWcm5ij4ZOalFgPFTcDiAUX5aanFxZn5eUhSZjCpgtQisPnmYIHgglSQCWARC7CIf0lGahFIh6VSbCwA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [LoB = _t, LoB_id = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"LoB", type text}, {"LoB_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

