table 'gold dim_record_type'
	lineageTag: bae349e9-ac07-4e84-824b-f268d840585f

	column record_id
		dataType: int64
		formatString: 0
		lineageTag: 786537ce-2984-4a8c-857e-0f2e7b76987d
		summarizeBy: sum
		sourceColumn: record_id

		annotation SummarizationSetBy = Automatic

	column record_type
		dataType: string
		lineageTag: 7e035318-9b68-4c5a-a130-9815981834ea
		summarizeBy: none
		sourceColumn: record_type
		sortByColumn: record_id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'gold dim_record_type' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfJLLVeK1YlWMgKyg1LzUssTc8B8YyDfvyQjtahYKTYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [record_id = _t, record_type = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"record_id", Int64.Type}, {"record_type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

